# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json tsconfig.json index.ts ./
COPY assets ./assets
# install dependencies and build
RUN npm install --ignore-scripts
RUN npm run build

FROM node:18-alpine AS release
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./package.json
ENV NODE_ENV=production
CMD ["node", "dist/index.js"]
